spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
      config:
        enabled: true
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/mall_swarm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver